module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [2, "always", ["feat", "fix", "docs", "style", "refactor", "perf", "test", "update"]],
  },
  prompt: {
    messages: {
      type: "选择你要提交的类型 :",
      subject: "填写本次提交的描述 :\n",
      confirmCommit: "是否提交或修改commit ?",
    },
    skipQuestions: ["scope", "customScope", "footerPrefix", "breaking", "footer", "body"],
    types: [
      { value: "feat", name: "feat:     ✨  新增功能", emoji: ":sparkles:" },
      { value: "fix", name: "fix:      🐛  修复缺陷", emoji: ":bug:" },
      { value: "docs", name: "docs:     📝  文档变更", emoji: ":memo:" },
      { value: "update", name: "update:    💄  代码更新", emoji: ":lipstick:" },
      { value: "refactor", name: "refactor: ♻️   代码重构（不包括 bug 修复、功能新增）", emoji: ":recycle:" },
      { value: "perf", name: "perf:     ⚡️   性能优化", emoji: ":zap:" },
      { value: "test", name: "test:     ✅  添加疏漏测试或已有测试改动", emoji: ":white_check_mark:" },
      {
        value: "build",
        name: "build:    📦️   构建流程、外部依赖变更（如升级 npm 包、修改 webpack 配置等）",
        emoji: ":package:",
      },
      { value: "ci", name: "ci:       🎡  修改 CI 配置、脚本", emoji: ":ferris_wheel:" },
      { value: "chore", name: "chore:    🔨  回滚 commit", emoji: ":hammer:" },
      {
        value: "revert",
        name: "revert:   ⏪️  对构建过程或辅助工具和库的更改（不影响源文件、测试用例）",
        emoji: ":rewind:",
      },
    ],
    useEmoji: true,
    emojiAlign: "center",
    useAI: false,
    aiNumber: 1,
    themeColorCode: "",
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: "bottom",
    customScopesAlias: "custom",
    emptyScopesAlias: "empty",
    upperCaseSubject: null,
    markBreakingChangeMode: false,
    allowBreakingChanges: ["feat", "fix"],
    breaklineNumber: 100,
    breaklineChar: "|",
    issuePrefixes: [{ value: "closed", name: "closed: ISSUES has been processed" }],
    customIssuePrefixAlign: "top",
    emptyIssuePrefixAlias: "skip",
    customIssuePrefixAlias: "custom",
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    scopeOverrides: undefined,
    defaultBody: "",
    defaultIssues: "",
    defaultScope: "",
    defaultSubject: "",
  },
};
